### ISSUE TITLE
Allow creating of new groups/categories

### ISSUE THREAD

**Issue by kanej** [Permaweb/permaweb#35]
Currently the `Create new group` button is disabled and the group listing shows only the home group where all articles are currently kept.

![image](https://user-images.githubusercontent.com/24030/63638630-b7033680-c682-11e9-900b-9b86cb72eb2c.png)

We should allow the adding of new categories and for articles to be associated with a category show that they show in the listing view when the category is clicked.

**Comment by AquiGorka** [comment]
@kanej for the time being we are not looking into categories as collections, only groups where the user adds other users they want to follow, does this task also refer to that?
